### PR TITLE
Bug report: suppressing substituted variables that are already rendered

### PR DESCRIPTION
**Pull request by larsgw**
I assumed "the rest" in

> Substituted variables are suppressed in the rest of the output to prevent duplication.

points to everything except this `cs:names`, not just everything after it. Is that correct? If so, then here's a bug report.

### CODE REVIEW

**Comment by bdarcus** [comment]
I think we need input from @fbennett here.

**Comment by fbennett** [comment]
As I read the specification, "the rest," must refer only to instances of the variable that follow. If rendering via `cs:substitute` were meant to be suppressed throughout the citation, further language would be required to specify the priority, if any, of two instances of `cs:names` that both attempt to render a variable through `cs:substitute`.

Apart from that gap in the language, at the implementation level a processor would need to render the entire citation to identify variables rendered through `cs:substitute`, and then either track down and remove other instances and associated punctuation from output, or re-render the entire citation in a second pass, suppressing output from non-`cs:substitute` instances of the variable. Not imposssible, but either option would be cumbersome to implement.

At the style design level, back-tracking variable suppression would make every straight render of a variable contingent, making it harder to interpret the intended effect of the CSL when read directly in a code editor.

**Comment by larsgw** [comment]
I don't really like it either, I suppose I should have phrased it differently: I'm fine with a clarification in the spec. Backtracing seems horrible.

**Comment by bdarcus** [comment]
> I'm fine with a clarification in the spec. Backtracing seems horrible.

Are you able to propose a PR for the spec?

**Comment by larsgw** [comment]
Is next week okay? I'm quite busy this weekend...

**Comment by bdarcus** [comment]
Of course; no rush.

**Comment by bdarcus** [comment]
I'm going to close this in favor of a clarification in the spec.

**Pull request closed without merging**
