### PR TITLE
Move `citation-number` test that depend on off-spec behavior to `off-spec` folder

### PR DESCRIPTION
**Pull request by Jason-Abbott**
Per conversation in https://github.com/citation-style-language/test-suite/issues/53#issuecomment-1588422238

Tests that show a reversed `citation-number` depend on overloaded behavior not defined in the specification. I left in place `citation-number` tests that show an ascending `citation-number`. I think those are basically no-ops anyway.

I considered updating `processor.py` with an argument to optionally include this folder but I’m not sure how often it’s used. It didn’t look like it was updated for the `processor-tests/humans/experiments` folder so maybe not needed.

### CODE REVIEW

**Comment by Jason-Abbott** [comment]
@bdarcus are you still seeing conflicts? In the GitHub interface, I’m seeing 
image

**Comment by bdarcus** [comment]
Oh wow; maybe a GitHub issue then.

Here's what I see:

Screenshot_20230619-121618

**Comment by Jason-Abbott** [comment]
Ah, one thing I just noticed … In the future, I need to PR from _branches_ on my fork. I made my test-suite fork a _submodule_ of my Swift processor project so whatever I see to adjust there is immediately incorporated into any open PR here — not quite what I intended. It also makes the commit description weird since I’m generally describing processor changes, not the test tweaks.

**Comment by Jason-Abbott** [comment]
Made new PR from branch #65

**Pull request closed without merging**
