### PR TITLE
Tidy up whitespaces in txt files

### PR DESCRIPTION
**Pull request by customcommander**
Hi- I've noticed some inconsistencies around whitespaces in the "sections delimiters" in the txt files. Here's some tidy up. Thanks.

### CODE REVIEW

**Comment by rmzelle** [comment]
@fbennett, can you review?

**Comment by customcommander** [comment]
@rmzelle @fbennett :-)

**Comment by customcommander** [comment]
@fbennett Anything I can do to get this PR through or do you think it isn't necessary?

**Comment by fbennett** [comment]
Sorry for the delay!

**Comment by rmzelle** [comment]
Thanks both!

**Pull request merged**
